module.exports = {
        c_query:{
                selectCategory: 'selectCategory',
                backCategory: 'backCategory',
                selectModel: 'sM',
                selectQuality: 'selectQuality',
                selectCase: 'selectCase',
                selectNoGravir: 'selectNoGravir',
                selectGravir: 'selectGravir',
                selectProduct: 'selectProduct',
                selectOrdering: 'selectOrdering',
                deleteOrdering: 'deleteOrdering',
                editCount: 'editCount',
                sendOrding: 'sendOrding',
                sendOrdingImei: 'sendOrdingImei',
                deleteImei: 'deleteImei',
                sendBasket: 'sendBasket',
                confirName: 'confirName',
                editName: 'editName',
                editCity: 'editCity',
                confirCity: 'confirCity',
                addApplic: 'addApplic',
                addApplicImei: 'addApplicImei',
                noApplicImei: 'noApplicImei',
                noApplic: 'noApplic',
                noActive: 'Не активный',
                noConfir: 'Обрабатывается',
                yesConfir: 'Подтвержден',
                gotConfir: 'gotConfir',
                cancelConfir: 'Отклонен',
                addImei: 'addImei',
                addImeiMemory: 'addImeiMemory',
                addImeiPart: 'addImeiPart',
                addImeiText: 'addImeiText',
                addImeiModel: 'addImeiModel',
                addImeiSerial: 'addImeiSerial',
                addImeiImei: 'addImeiImei',
                addScreenImei: 'addScreenImei',
                succfullydel: 'Успешно доставлено',
                presenceProduct: 'presenceProduct',
                individualPrice: 'individualPrice',
                selectindividualPrice: 'selectindividualPrice',
                wayIndivId: 'wayIndivId',
                wayIndivPrice: 'wayIndivPrice',
                wayEditPrice: 'wayEditPrice',
                selectType: 'selectType',
                addComment: 'addComment'
        }
}

